

#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Genre {
    Blues = 0,
    ClassicRock = 1,
    Country = 2,
    Dance = 3,
    Disco = 4,
    Funk = 5,
    Grunge = 6,
    HipHop = 7,
    Jazz = 8,
    Metal = 9,
    NewAge = 10,
    Oldies = 11,
    Other = 12,
    Pop = 13,
    RnB = 14,
    Rap = 15,
    Reggae = 16,
    Rock = 17,
    Techno = 18,
    Industrial = 19,
    Alternative = 20,
    Ska = 21,
    DeathMetal = 22,
    Pranks = 23,
    Soundtrack = 24,
    EuroTechno = 25,
    Ambient = 26,
    TripHop = 27,
    Vocal = 28,
    JazzFunk = 29,
    Fusion = 30,
    Trance = 31,
    Classical = 32,
    Instrumental = 33,
    Acid = 34,
    House = 35,
    Game = 36,
    SoundClip = 37,
    Gospel = 38,
    Noise = 39,
    AltRock = 40,
    Bass = 41,
    Soul = 42,
    Punk = 43,
    Space = 44,
    Meditative = 45,
    InstrumentalPop = 46,
    InstrumentalRock = 47,
    Ethnic = 48,
    Gothic = 49,
    Darkwave = 50,
    TechnoIndustrial = 51,
    Electronic = 52,
    PopFolk = 53,
    Eurodance = 54,
    Dream = 55,
    SouthernRock = 56,
    Comedy = 57,
    Cult = 58,
    GangstaRap = 59,
    Top40 = 60,
    ChristianRap = 61,
    PopFunk = 62,
    Jungle = 63,
    NativeAmerican = 64,
    Cabaret = 65,
    NewWave = 66,
    Psychedelic = 67,
    Rave = 68,
    Showtunes = 69,
    Trailer = 70,
    LoFi = 71,
    Tribal = 72,
    AcidPunk = 73,
    AcidJazz = 74,
    Polka = 75,
    Retro = 76,
    Musical = 77,
    RockAndRoll = 78,
    HardRock = 79,
    Folk = 80,
    FolkRock = 81,
    NationalFolk = 82,
    Swing = 83,
    FastFusion = 84,
    Bebop = 85,
    Latin = 86,
    Revival = 87,
    Celtic = 88,
    Bluegrass = 89,
    Avantgarde = 90,
    GothicRock = 91,
    ProgressiveRock = 92,
    PsychedelicRock = 93,
    SymphonicRock = 94,
    SlowRock = 95,
    BigBand = 96,
    Chorus = 97,
    EasyListening = 98,
    Acoustic = 99,
    Humour = 100,
    Speech = 101,
    Chanson = 102,
    Opera = 103,
    ChamberMusic = 104,
    Sonata = 105,
    Symphony = 106,
    BootyBass = 107,
    Primus = 108,
    PornGroove = 109,
    Satire = 110,
    SlowJam = 111,
    Club = 112,
    Tango = 113,
    Samba = 114,
    Folklore = 115,
    Ballad = 116,
    PowerBallad = 117,
    RhythmicSoul = 118,
    Freestyle = 119,
    Duet = 120,
    PunkRock = 121,
    DrumSolo = 122,
    ACappella = 123,
    EuroHouse = 124,
    DanceHall = 125,
    Goa = 126,
    DrumAndBass = 127,
    ClubHouse = 128,
    Hardcore = 129,
    Terror = 130,
    Indie = 131,
    BritPop = 132,
    AfroPunk = 133,
    PolskPunk = 134,
    Beat = 135,
    ChristianGangstaRap = 136,
    HeavyMetal = 137,
    BlackMetal = 138,
    Crossover = 139,
    ContemporaryChristian = 140,
    ChristianRock = 141,
    Merengue = 142,
    Salsa = 143,
    ThrashMetal = 144,
    Anime = 145,
    JPop = 146,
    Synthpop = 147,
    Abstract = 148,
    ArtRock = 149,
    Baroque = 150,
    Bhangra = 151,
    BigBeat = 152,
    Breakbeat = 153,
    Chillout = 154,
    Downtempo = 155,
    Dub = 156,
    EBM = 157,
    Eclectic = 158,
    Electro = 159,
    Electroclash = 160,
    Emo = 161,
    Experimental = 162,
    Garage = 163,
    Global = 164,
    IDM = 165,
    Illbient = 166,
    IndustroGoth = 167,
    JamBand = 168,
    Krautrock = 169,
    Leftfield = 170,
    Lounge = 171,
    MathRock = 172,
    NewRomantic = 173,
    NuBreakz = 174,
    PostPunk = 175,
    PostRock = 176,
    Psytrance = 177,
    Shoegaze = 178,
    SpaceRock = 179,
    TropRock = 180,
    WorldMusic = 181,
    Neoclassical = 182,
    Audiobook = 183,
    AudioTheatre = 184,
    NeueDeutscheWelle = 185,
    Podcast = 186,
    IndieRock = 187,
    GFunk = 188,
    Dubstep = 189,
    GarageRock = 190,
    Psybient = 191,
    Unknown,
    None = 255,
}


impl Genre {
    pub fn from_u8(value: u8) -> Self {
        match value {
            0 => Self::Blues,
            1 => Self::ClassicRock,
            2 => Self::Country,
            3 => Self::Dance,
            4 => Self::Disco,
            5 => Self::Funk,
            6 => Self::Grunge,
            7 => Self::HipHop,
            8 => Self::Jazz,
            9 => Self::Metal,
            10 => Self::NewAge,
            11 => Self::Oldies,
            12 => Self::Other,
            13 => Self::Pop,
            14 => Self::RnB,
            15 => Self::Rap,
            16 => Self::Reggae,
            17 => Self::Rock,
            18 => Self::Techno,
            19 => Self::Industrial,
            20 => Self::Alternative,
            21 => Self::Ska,
            22 => Self::DeathMetal,
            23 => Self::Pranks,
            24 => Self::Soundtrack,
            25 => Self::EuroTechno,
            26 => Self::Ambient,
            27 => Self::TripHop,
            28 => Self::Vocal,
            29 => Self::JazzFunk,
            30 => Self::Fusion,
            31 => Self::Trance,
            32 => Self::Classical,
            33 => Self::Instrumental,
            34 => Self::Acid,
            35 => Self::House,
            36 => Self::Game,
            37 => Self::SoundClip,
            38 => Self::Gospel,
            39 => Self::Noise,
            40 => Self::AltRock,
            41 => Self::Bass,
            42 => Self::Soul,
            43 => Self::Punk,
            44 => Self::Space,
            45 => Self::Meditative,
            46 => Self::InstrumentalPop,
            47 => Self::InstrumentalRock,
            48 => Self::Ethnic,
            49 => Self::Gothic,
            50 => Self::Darkwave,
            51 => Self::TechnoIndustrial,
            52 => Self::Electronic,
            53 => Self::PopFolk,
            54 => Self::Eurodance,
            55 => Self::Dream,
            56 => Self::SouthernRock,
            57 => Self::Comedy,
            58 => Self::Cult,
            59 => Self::GangstaRap,
            60 => Self::Top40,
            61 => Self::ChristianRap,
            62 => Self::PopFunk,
            63 => Self::Jungle,
            64 => Self::NativeAmerican,
            65 => Self::Cabaret,
            66 => Self::NewWave,
            67 => Self::Psychedelic,
            68 => Self::Rave,
            69 => Self::Showtunes,
            70 => Self::Trailer,
            71 => Self::LoFi,
            72 => Self::Tribal,
            73 => Self::AcidPunk,
            74 => Self::AcidJazz,
            75 => Self::Polka,
            76 => Self::Retro,
            77 => Self::Musical,
            78 => Self::RockAndRoll,
            79 => Self::HardRock,
            80 => Self::Folk,
            81 => Self::FolkRock,
            82 => Self::NationalFolk,
            83 => Self::Swing,
            84 => Self::FastFusion,
            85 => Self::Bebop,
            86 => Self::Latin,
            87 => Self::Revival,
            88 => Self::Celtic,
            89 => Self::Bluegrass,
            90 => Self::Avantgarde,
            91 => Self::GothicRock,
            92 => Self::ProgressiveRock,
            93 => Self::PsychedelicRock,
            94 => Self::SymphonicRock,
            95 => Self::SlowRock,
            96 => Self::BigBand,
            97 => Self::Chorus,
            98 => Self::EasyListening,
            99 => Self::Acoustic,
            100 => Self::Humour,
            101 => Self::Speech,
            102 => Self::Chanson,
            103 => Self::Opera,
            104 => Self::ChamberMusic,
            105 => Self::Sonata,
            106 => Self::Symphony,
            107 => Self::BootyBass,
            108 => Self::Primus,
            109 => Self::PornGroove,
            110 => Self::Satire,
            111 => Self::SlowJam,
            112 => Self::Club,
            113 => Self::Tango,
            114 => Self::Samba,
            115 => Self::Folklore,
            116 => Self::Ballad,
            117 => Self::PowerBallad,
            118 => Self::RhythmicSoul,
            119 => Self::Freestyle,
            120 => Self::Duet,
            121 => Self::PunkRock,
            122 => Self::DrumSolo,
            123 => Self::ACappella,
            124 => Self::EuroHouse,
            125 => Self::DanceHall,
            126 => Self::Goa,
            127 => Self::DrumAndBass,
            128 => Self::ClubHouse,
            129 => Self::Hardcore,
            130 => Self::Terror,
            131 => Self::Indie,
            132 => Self::BritPop,
            133 => Self::AfroPunk,
            134 => Self::PolskPunk,
            135 => Self::Beat,
            136 => Self::ChristianGangstaRap,
            137 => Self::HeavyMetal,
            138 => Self::BlackMetal,
            139 => Self::Crossover,
            140 => Self::ContemporaryChristian,
            141 => Self::ChristianRock,
            142 => Self::Merengue,
            143 => Self::Salsa,
            144 => Self::ThrashMetal,
            145 => Self::Anime,
            146 => Self::JPop,
            147 => Self::Synthpop,
            148 => Self::Abstract,
            149 => Self::ArtRock,
            150 => Self::Baroque,
            151 => Self::Bhangra,
            152 => Self::BigBeat,
            153 => Self::Breakbeat,
            154 => Self::Chillout,
            155 => Self::Downtempo,
            156 => Self::Dub,
            157 => Self::EBM,
            158 => Self::Eclectic,
            159 => Self::Electro,
            160 => Self::Electroclash,
            161 => Self::Emo,
            162 => Self::Experimental,
            163 => Self::Garage,
            164 => Self::Global,
            165 => Self::IDM,
            166 => Self::Illbient,
            167 => Self::IndustroGoth,
            168 => Self::JamBand,
            169 => Self::Krautrock,
            170 => Self::Leftfield,
            171 => Self::Lounge,
            172 => Self::MathRock,
            173 => Self::NewRomantic,
            174 => Self::NuBreakz,
            175 => Self::PostPunk,
            176 => Self::PostRock,
            177 => Self::Psytrance,
            178 => Self::Shoegaze,
            179 => Self::SpaceRock,
            180 => Self::TropRock,
            181 => Self::WorldMusic,
            182 => Self::Neoclassical,
            183 => Self::Audiobook,
            184 => Self::AudioTheatre,
            185 => Self::NeueDeutscheWelle,
            186 => Self::Podcast,
            187 => Self::IndieRock,
            188 => Self::GFunk,
            189 => Self::Dubstep,
            190 => Self::GarageRock,
            191 => Self::Psybient,
            255 => Self::None,
            _ => Self::Unknown,
        }
    }
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Blues => "Blues",
            Self::ClassicRock => "Classic Rock",
            Self::Country => "Country",
            Self::Dance => "Dance",
            Self::Disco => "Disco",
            Self::Funk => "Funk",
            Self::Grunge => "Grunge",
            Self::HipHop => "Hip-Hop",
            Self::Jazz => "Jazz",
            Self::Metal => "Metal",
            Self::NewAge => "New Age",
            Self::Oldies => "Oldies",
            Self::Other => "Other",
            Self::Pop => "Pop",
            Self::RnB => "R&B",
            Self::Rap => "Rap",
            Self::Reggae => "Reggae",
            Self::Rock => "Rock",
            Self::Techno => "Techno",
            Self::Industrial => "Industrial",
            Self::Alternative => "Alternative",
            Self::Ska => "Ska",
            Self::DeathMetal => "Death Metal",
            Self::Pranks => "Pranks",
            Self::Soundtrack => "Soundtrack",
            Self::EuroTechno => "Euro-Techno",
            Self::Ambient => "Ambient",
            Self::TripHop => "Trip-Hop",
            Self::Vocal => "Vocal",
            Self::JazzFunk => "Jazz+Funk",
            Self::Fusion => "Fusion",
            Self::Trance => "Trance",
            Self::Classical => "Classical",
            Self::Instrumental => "Instrumental",
            Self::Acid => "Acid",
            Self::House => "House",
            Self::Game => "Game",
            Self::SoundClip => "Sound Clip",
            Self::Gospel => "Gospel",
            Self::Noise => "Noise",
            Self::AltRock => "Alt. Rock",
            Self::Bass => "Bass",
            Self::Soul => "Soul",
            Self::Punk => "Punk",
            Self::Space => "Space",
            Self::Meditative => "Meditative",
            Self::InstrumentalPop => "Instrumental Pop",
            Self::InstrumentalRock => "Instrumental Rock",
            Self::Ethnic => "Ethnic",
            Self::Gothic => "Gothic",
            Self::Darkwave => "Darkwave",
            Self::TechnoIndustrial => "Techno-Industrial",
            Self::Electronic => "Electronic",
            Self::PopFolk => "Pop-Folk",
            Self::Eurodance => "Eurodance",
            Self::Dream => "Dream",
            Self::SouthernRock => "Southern Rock",
            Self::Comedy => "Comedy",
            Self::Cult => "Cult",
            Self::GangstaRap => "Gangsta Rap",
            Self::Top40 => "Top 40",
            Self::ChristianRap => "Christian Rap",
            Self::PopFunk => "Pop/Funk",
            Self::Jungle => "Jungle",
            Self::NativeAmerican => "Native American",
            Self::Cabaret => "Cabaret",
            Self::NewWave => "New Wave",
            Self::Psychedelic => "Psychedelic",
            Self::Rave => "Rave",
            Self::Showtunes => "Showtunes",
            Self::Trailer => "Trailer",
            Self::LoFi => "Lo-Fi",
            Self::Tribal => "Tribal",
            Self::AcidPunk => "Acid Punk",
            Self::AcidJazz => "Acid Jazz",
            Self::Polka => "Polka",
            Self::Retro => "Retro",
            Self::Musical => "Musical",
            Self::RockAndRoll => "Rock & Roll",
            Self::HardRock => "Hard Rock",
            Self::Folk => "Folk",
            Self::FolkRock => "Folk-Rock",
            Self::NationalFolk => "National Folk",
            Self::Swing => "Swing",
            Self::FastFusion => "Fast-Fusion",
            Self::Bebop => "Bebop",
            Self::Latin => "Latin",
            Self::Revival => "Revival",
            Self::Celtic => "Celtic",
            Self::Bluegrass => "Bluegrass",
            Self::Avantgarde => "Avantgarde",
            Self::GothicRock => "Gothic Rock",
            Self::ProgressiveRock => "Progressive Rock",
            Self::PsychedelicRock => "Psychedelic Rock",
            Self::SymphonicRock => "Symphonic Rock",
            Self::SlowRock => "Slow Rock",
            Self::BigBand => "Big Band",
            Self::Chorus => "Chorus",
            Self::EasyListening => "Easy Listening",
            Self::Acoustic => "Acoustic",
            Self::Humour => "Humour",
            Self::Speech => "Speech",
            Self::Chanson => "Chanson",
            Self::Opera => "Opera",
            Self::ChamberMusic => "Chamber Music",
            Self::Sonata => "Sonata",
            Self::Symphony => "Symphony",
            Self::BootyBass => "Booty Bass",
            Self::Primus => "Primus",
            Self::PornGroove => "Porn Groove",
            Self::Satire => "Satire",
            Self::SlowJam => "Slow Jam",
            Self::Club => "Club",
            Self::Tango => "Tango",
            Self::Samba => "Samba",
            Self::Folklore => "Folklore",
            Self::Ballad => "Ballad",
            Self::PowerBallad => "Power Ballad",
            Self::RhythmicSoul => "Rhythmic Soul",
            Self::Freestyle => "Freestyle",
            Self::Duet => "Duet",
            Self::PunkRock => "Punk Rock",
            Self::DrumSolo => "Drum Solo",
            Self::ACappella => "A Cappella",
            Self::EuroHouse => "Euro-House",
            Self::DanceHall => "Dance Hall",
            Self::Goa => "Goa",
            Self::DrumAndBass => "Drum & Bass",
            Self::ClubHouse => "Club-House",
            Self::Hardcore => "Hardcore",
            Self::Terror => "Terror",
            Self::Indie => "Indie",
            Self::BritPop => "BritPop",
            Self::AfroPunk => "Afro-Punk",
            Self::PolskPunk => "Polsk Punk",
            Self::Beat => "Beat",
            Self::ChristianGangstaRap => "Christian Gangsta Rap",
            Self::HeavyMetal => "Heavy Metal",
            Self::BlackMetal => "Black Metal",
            Self::Crossover => "Crossover",
            Self::ContemporaryChristian => "Contemporary Christian",
            Self::ChristianRock => "Christian Rock",
            Self::Merengue => "Merengue",
            Self::Salsa => "Salsa",
            Self::ThrashMetal => "Thrash Metal",
            Self::Anime => "Anime",
            Self::JPop => "JPop",
            Self::Synthpop => "Synthpop",
            Self::Abstract => "Abstract",
            Self::ArtRock => "Art Rock",
            Self::Baroque => "Baroque",
            Self::Bhangra => "Bhangra",
            Self::BigBeat => "Big Beat",
            Self::Breakbeat => "Breakbeat",
            Self::Chillout => "Chillout",
            Self::Downtempo => "Downtempo",
            Self::Dub => "Dub",
            Self::EBM => "EBM",
            Self::Eclectic => "Eclectic",
            Self::Electro => "Electro",
            Self::Electroclash => "Electroclash",
            Self::Emo => "Emo",
            Self::Experimental => "Experimental",
            Self::Garage => "Garage",
            Self::Global => "Global",
            Self::IDM => "IDM",
            Self::Illbient => "Illbient",
            Self::IndustroGoth => "Industro-Goth",
            Self::JamBand => "Jam Band",
            Self::Krautrock => "Krautrock",
            Self::Leftfield => "Leftfield",
            Self::Lounge => "Lounge",
            Self::MathRock => "Math Rock",
            Self::NewRomantic => "New Romantic",
            Self::NuBreakz => "Nu-Breakz",
            Self::PostPunk => "Post-Punk",
            Self::PostRock => "Post-Rock",
            Self::Psytrance => "Psytrance",
            Self::Shoegaze => "Shoegaze",
            Self::SpaceRock => "Space Rock",
            Self::TropRock => "Trop Rock",
            Self::WorldMusic => "World Music",
            Self::Neoclassical => "Neoclassical",
            Self::Audiobook => "Audiobook",
            Self::AudioTheatre => "Audio Theatre",
            Self::NeueDeutscheWelle => "Neue Deutsche Welle",
            Self::Podcast => "Podcast",
            Self::IndieRock => "Indie Rock",
            Self::GFunk => "G-Funk",
            Self::Dubstep => "Dubstep",
            Self::GarageRock => "Garage Rock",
            Self::Psybient => "Psybient",
            Self::None => "None",
            Self::Unknown => "Unknown Genre"
        }
    }
}
// 0 = Blues
// 1 = Classic Rock
// 2 = Country
// 3 = Dance
// 4 = Disco
// 5 = Funk
// 6 = Grunge
// 7 = Hip-Hop
// 8 = Jazz
// 9 = Metal
// 10 = New Age
// 11 = Oldies
// 12 = Other
// 13 = Pop
// 14 = R&B
// 15 = Rap
// 16 = Reggae
// 17 = Rock
// 18 = Techno
// 19 = Industrial
// 20 = Alternative
// 21 = Ska
// 22 = Death Metal
// 23 = Pranks
// 24 = Soundtrack
// 25 = Euro-Techno
// 26 = Ambient
// 27 = Trip-Hop
// 28 = Vocal
// 29 = Jazz+Funk
// 30 = Fusion
// 31 = Trance
// 32 = Classical
// 33 = Instrumental
// 34 = Acid
// 35 = House
// 36 = Game
// 37 = Sound Clip
// 38 = Gospel
// 39 = Noise
// 40 = Alt. Rock
// 41 = Bass
// 42 = Soul
// 43 = Punk
// 44 = Space
// 45 = Meditative
// 46 = Instrumental Pop
// 47 = Instrumental Rock
// 48 = Ethnic
// 49 = Gothic
// 50 = Darkwave
// 51 = Techno-Industrial
// 52 = Electronic
// 53 = Pop-Folk
// 54 = Eurodance
// 55 = Dream
// 56 = Southern Rock
// 57 = Comedy
// 58 = Cult
// 59 = Gangsta Rap
// 60 = Top 40
// 61 = Christian Rap
// 62 = Pop/Funk
// 63 = Jungle
// 64 = Native American	  	65 = Cabaret
// 66 = New Wave
// 67 = Psychedelic
// 68 = Rave
// 69 = Showtunes
// 70 = Trailer
// 71 = Lo-Fi
// 72 = Tribal
// 73 = Acid Punk
// 74 = Acid Jazz
// 75 = Polka
// 76 = Retro
// 77 = Musical
// 78 = Rock & Roll
// 79 = Hard Rock
// 80 = Folk
// 81 = Folk-Rock
// 82 = National Folk
// 83 = Swing
// 84 = Fast-Fusion
// 85 = Bebop
// 86 = Latin
// 87 = Revival
// 88 = Celtic
// 89 = Bluegrass
// 90 = Avantgarde
// 91 = Gothic Rock
// 92 = Progressive Rock
// 93 = Psychedelic Rock
// 94 = Symphonic Rock
// 95 = Slow Rock
// 96 = Big Band
// 97 = Chorus
// 98 = Easy Listening
// 99 = Acoustic
// 100 = Humour
// 101 = Speech
// 102 = Chanson
// 103 = Opera
// 104 = Chamber Music
// 105 = Sonata
// 106 = Symphony
// 107 = Booty Bass
// 108 = Primus
// 109 = Porn Groove
// 110 = Satire
// 111 = Slow Jam
// 112 = Club
// 113 = Tango
// 114 = Samba
// 115 = Folklore
// 116 = Ballad
// 117 = Power Ballad
// 118 = Rhythmic Soul
// 119 = Freestyle
// 120 = Duet
// 121 = Punk Rock
// 122 = Drum Solo
// 123 = A Cappella
// 124 = Euro-House
// 125 = Dance Hall
// 126 = Goa
// 127 = Drum & Bass
// 128 = Club-House
// 129 = Hardcore	  	130 = Terror
// 131 = Indie
// 132 = BritPop
// 133 = Afro-Punk
// 134 = Polsk Punk
// 135 = Beat
// 136 = Christian Gangsta Rap
// 137 = Heavy Metal
// 138 = Black Metal
// 139 = Crossover
// 140 = Contemporary Christian
// 141 = Christian Rock
// 142 = Merengue
// 143 = Salsa
// 144 = Thrash Metal
// 145 = Anime
// 146 = JPop
// 147 = Synthpop
// 148 = Abstract
// 149 = Art Rock
// 150 = Baroque
// 151 = Bhangra
// 152 = Big Beat
// 153 = Breakbeat
// 154 = Chillout
// 155 = Downtempo
// 156 = Dub
// 157 = EBM
// 158 = Eclectic
// 159 = Electro
// 160 = Electroclash
// 161 = Emo
// 162 = Experimental
// 163 = Garage
// 164 = Global
// 165 = IDM
// 166 = Illbient
// 167 = Industro-Goth
// 168 = Jam Band
// 169 = Krautrock
// 170 = Leftfield
// 171 = Lounge
// 172 = Math Rock
// 173 = New Romantic
// 174 = Nu-Breakz
// 175 = Post-Punk
// 176 = Post-Rock
// 177 = Psytrance
// 178 = Shoegaze
// 179 = Space Rock
// 180 = Trop Rock
// 181 = World Music
// 182 = Neoclassical
// 183 = Audiobook
// 184 = Audio Theatre
// 185 = Neue Deutsche Welle
// 186 = Podcast
// 187 = Indie Rock
// 188 = G-Funk
// 189 = Dubstep
// 190 = Garage Rock
// 191 = Psybient
// 255 = None